### ISSUE TITLE
No paths and definitions

### ISSUE THREAD

**Issue by mquekel** [pintle/pintle-swagger#2]
Hi, I am trying to use Swagger in a Sitecore 9.0.2 environment. But I don't see any controllers after installing the Pintle.Swagger Nuget package.

Both the Sitecore and Custom endpoints are empty.

URL: /swagger/docs/custom
Response:
`
{
   "swagger":"2.0",
   "info":{
      "version":"custom",
      "title":"Custom Web API services"
   },
   "host":"local-contentapi",
   "schemes":[
      "http"
   ],
   "paths":{  },
   "definitions":{   }
`

URL: URL: /swagger/docs/sitecore
Response:
`
{
   "swagger":"2.0",
   "info":{
      "version":"sitecore",
      "title":"Sitecore Web API services"
   },
   "host":"local-contentapi",
   "schemes":[
      "http"
   ],
   "paths":{   },
   "definitions":{   }
}
`

**Comment by mquekel** [comment]
Found out that the issue was caused by our custom implementation of the IHttpControllerSelector. 
This issue can be closed.

**Comment by vhil** [comment]
Good, you can also check [Pintle.Swagger.Settings.config](https://github.com/pintle/pintle-swagger/blob/master/src/Pintle.Swagger/App_Config/Include/Feature/Pintle.Swagger/Pintle.Swagger.Settings.config) and manipulate your route prefixes like `<custom name="custom" routeTemplate="api/v1" description="Custom Web API services"/>` in case you are using different prefix(es) then `api/v1`
